// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpoalupemsjspnhcrfzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwb2FsdXBlbXNqc3BuaGNyZnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjUxMzIsImV4cCI6MjA2MzkwMTEzMn0.HKlaQO91FetvqaSTDiLfUGU5AlX8cmWRK7fvv98hMlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);